# Generated by Django 4.1.7 on 2023-03-14 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_company_project_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="projects.company",
            ),
        ),
    ]
